title: Basic Nosense
author: fsantibanezleal
email: fasl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Boring info.

# social links
twitter_username: fsantiba # DO NOT include the @ character, or else the build will fail!
github_username:  fsantibanezleal # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
